apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react.fullname" . }}-nginx-config
  labels:
    {{- include "react.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        root {{ .Values.react.config.webRoot }};

        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Enable browser caching for static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Deny access to . files
        location ~ /\. {
            deny all;
        }
    }
