apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react.fullname" . }}
  labels:
    {{- include "react.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "react.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "react.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.sharedVolume.name }}
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "react.fullname" . }}-nginx-config
      initContainers:
        - name: data-container
          image: "{{ .Values.dataImage.repository }}:{{ .Values.dataImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.dataImage.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying React application files to shared volume..."
              cp -r /app/. /data/
          volumeMounts:
            - name: {{ .Values.sharedVolume.name }}
              mountPath: /data
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.sharedVolume.name }}
              mountPath: {{ .Values.react.config.webRoot }}
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
