apiVersion: v2
name: react
description: A Helm chart for React applications
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - react
  - frontend
  - javascript
maintainers:
  - name: Unframed
