## Global settings
nameOverride: ""
fullnameOverride: ""

## Nginx image
nginxImage:
  repository: rg.nl-ams.scw.cloud/unframed-container-registry/nginx
  tag: "latest"
  pullPolicy: IfNotPresent

## Data container for application files
dataImage:
  repository: rg.nl-ams.scw.cloud/unframed-container-registry/dummy_page
  tag: "latest"
  pullPolicy: IfNotPresent

## Application settings
react:
  config:
    webRoot: "/var/www/html"

## Shared volume settings
sharedVolume:
  name: app-data

## Scaling settings
replicaCount: 1

## Service settings
service:
  type: ClusterIP
  port: 8080

## Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

## Resource settings
resources:
  nginx:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

## Pod settings
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 33
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 33
  seccompProfile:
    type: RuntimeDefault
nodeSelector: {}
tolerations: []
affinity: {}
