apiVersion: v2
name: yii2
description: A Helm chart for Yii2 PHP Framework applications with ArgoCD Sync Waves support
type: application
version: 0.11.0
appVersion: "1.0.0"
keywords:
  - yii2
  - php
  - framework
  - web
  - argocd
  - sync-waves
maintainers:
  - name: Unframed
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common
