## Global settings
nameOverride: ""
fullnameOverride: ""


## Image settings
phpImage:
  repository: ghcr.io/unframed-nl/tooling-docker-containers/php
  tag: "8.1"
  pullPolicy: IfNotPresent

## Nginx image for serving WordPress
nginxImage:
  repository: ghcr.io/unframed-nl/tooling-docker-containers/nginx
  tag: "latest"
  pullPolicy: IfNotPresent

## Data container for application files
dataImage:
  repository: ghcr.io/unframed-nl/hosting-dummy-page
  tag: "latest"
  pullPolicy: IfNotPresent

## Application settings
yii2:
  env:
    YII_DEBUG: "false"
    YII_ENV: production
  config:
    webRoot: "/var/www/html/web"

## Shared volume settings
sharedVolume:
  name: app-data

## Scaling settings
replicaCount: 1

## Service settings
service:
  type: ClusterIP
  port: 8080

## Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

## Resource settings
resources:
  php:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  nginx:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  init:
    requests:
      cpu: 10m
      memory: 32Mi

## Probe settings
probes:
  liveness:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    path: /
    port: 8080
  readiness:
    enabled: false
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    path: /
    port: 8080
  startup:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1
    path: /
    port: 8080

## Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## Redis cache settings
redis:
  enabled: false
  image:
    repository: redis
    tag: "7.0-alpine"
    pullPolicy: IfNotPresent
  auth:
    enabled: false
    password: ""
  persistence:
    enabled: false
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
  config:
    maxmemory: "100mb"
    maxmemoryPolicy: "allkeys-lru"

## Queue workers configuration
## Each worker runs "php yii <name>/listen" in a PHP container
queueWorkers:
  enabled: false
  # List of queue workers to deploy
  workers: []
  # - name: queue       # Worker name (used in command: php yii <name>/listen)
  #   replicas: 1       # Number of worker replicas
  #   resources:        # Optional resource limits and requests
  #     limits:
  #       cpu: 500m
  #       memory: 512Mi
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi

## Cron jobs configuration
cronJobs:
  enabled: false
  # List of cron jobs to deploy
  jobs: []
  # - name: example-cron        # Cron job name
  #   schedule: "*/5 * * * *"   # Cron schedule expression
  #   command: "php yii example/command"  # Command to run
  #   resources:                # Optional resource limits and requests
  #     limits:
  #       cpu: 500m
  #       memory: 512Mi
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi

## Database configuration for DB Operator
## When enabled, creates a Database CRD and automatically mounts the generated secret
database:
  enabled: false
  # Name of the database cluster instance (required when enabled)
  instance: ""
  # Name of the database to create (required when enabled)
  name: ""
  # Whether to enable deletion protection for the database
  deletionProtected: true
  # Custom secret templates for MySQL database credentials
  secretsTemplates:
    DB_HOST: "{{ .DatabaseHost }}"
    DB_PORT: "{{ .DatabasePort }}"
    DB_DATABASE: "{{ .DatabaseName }}"
    DB_USERNAME: "{{ .UserName }}"
    DB_PASSWORD: "{{ .Password }}"

## Secret mounts configuration
## Reference existing secrets and mount their keys as environment variables
secretMounts: []
# - secretName: "yii2-db-credentials"
#   keys:
#     # Simple key (no renaming)
#     - "DB_USERNAME"
#     - "DB_PASSWORD"
#     - "DB_HOST"
#     # Key with renaming (from -> to)
#     - from: "DB_DATABASE"
#       to: "DB_NAME"


## Pod settings
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 33
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 33
  seccompProfile:
    type: RuntimeDefault
nodeSelector: {}
tolerations: []
affinity: {}
