## Global settings
nameOverride: ""
fullnameOverride: ""

## Image settings
phpImage:
  repository: registry.scaleway.com/unframed/php
  tag: "8.1-fpm"
  pullPolicy: IfNotPresent

## Nginx image for serving Laravel
nginxImage:
  repository: registry.scaleway.com/unframed/nginx
  tag: "stable-alpine"
  pullPolicy: IfNotPresent

## Data container for application files
dataImage:
  repository: registry.scaleway.com/unframed/laravel-data
  tag: "latest"
  pullPolicy: IfNotPresent

## Application settings
laravel:
  env:
    APP_NAME: Laravel
    APP_ENV: production
    APP_KEY: ""
    APP_DEBUG: "false"
    APP_URL: https://example.com
    
    LOG_CHANNEL: stack
    LOG_LEVEL: debug
    
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: laravel
    DB_USERNAME: laravel
    DB_PASSWORD: ""
    
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: sync
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
  
  # Laravel specific settings
  config:
    webRoot: "/var/www/html/public"

## Shared volume settings
sharedVolume:
  name: app-data

## Scaling settings
replicaCount: 1

## Service settings
service:
  type: ClusterIP
  port: 80

## Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

## Resource settings
resources:
  php:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  nginx:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

## MySQL database settings
mysql:
  enabled: true
  auth:
    database: laravel
    username: laravel
    password: ""
    rootPassword: ""
  primary:
    persistence:
      enabled: true
      size: 8Gi

## Pod settings
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
nodeSelector: {}
tolerations: []
affinity: {}
