## Common chart values
## This file contains default values that can be overridden by individual charts

## Redis cache settings
redis:
  enabled: false
  image:
    repository: redis
    tag: "7.0-alpine"
    pullPolicy: IfNotPresent
  auth:
    enabled: false
  password: ""
  persistence:
    enabled: false
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
  config:
    maxmemory: "100mb"
    maxmemoryPolicy: "allkeys-lru"

## Postgres (CloudNativePG) settings
postgres:
  enabled: false
  cnpg:
    description: ""
    cluster:
      imageName: ghcr.io/cloudnative-pg/postgresql:16
      instances: 2
      resources: {}
      storage:
        size: 10Gi
        storageClassName: ""
      bootstrap:
        initdb:
          database: app
          owner: app
          secret:
            name: ""
      monitoring:
        enabled: false
      postgresql: {}
    backup:
      enabled: false
      retentionPolicy: "7d"
      schedule: "0 3 * * *"
      s3:
        destinationPath: ""
        endpoint: s3.amazonaws.com
        region: ""
        wal:
          compression: ""
        s3Credentials:
          existingSecret: ""
          accessKeyId: ""
          secretAccessKey: ""
