apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
    {{- include "wordpress-bedrock.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress-bedrock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress-bedrock.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.sharedVolume.name }}
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "wordpress-bedrock.fullname" . }}-nginx-config
      initContainers:
        - name: data-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dataImage.repository }}:{{ .Values.dataImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.dataImage.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying application files to shared volume..."
              cp -r /app/. /data/
          volumeMounts:
            - name: {{ .Values.sharedVolume.name }}
              mountPath: /data
          resources:
            {{- toYaml .Values.resources.init | nindent 12 }}
      containers:
        - name: php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.phpImage.repository }}:{{ .Values.phpImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.phpImage.pullPolicy }}
          env:
            {{- range $key, $value := .Values.wordpress.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            # Redis environment variables for W3 Total Cache
            - name: WP_REDIS_HOST
              value: {{ include "wordpress-bedrock.fullname" . }}-redis
            - name: WP_REDIS_PORT
              value: {{ .Values.redis.service.port | quote }}
            {{- if .Values.redis.auth.enabled }}
            - name: WP_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-bedrock.fullname" . }}-redis
                  key: redis-password
            {{- end }}
            - name: WP_REDIS_TIMEOUT
              value: "1"
            - name: WP_REDIS_READ_TIMEOUT
              value: "1"
            - name: WP_REDIS_DATABASE
              value: "0"
            {{- end }}
            {{- if .Values.secretMounts }}
            # Mount secrets as environment variables
            {{- range $secretConfig := .Values.secretMounts }}
            {{- if $secretConfig.secretName }}
            {{- range $keyMapping := $secretConfig.keys }}
            {{- if kindIs "string" $keyMapping }}
            # Simple key (no renaming)
            - name: {{ $keyMapping }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretConfig.secretName }}
                  key: {{ $keyMapping }}
            {{- else }}
            # Key with renaming (from -> to)
            - name: {{ $keyMapping.to }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretConfig.secretName }}
                  key: {{ $keyMapping.from }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.sharedVolume.name }}
              mountPath: /var/www/html
          resources:
            {{- toYaml .Values.resources.php | nindent 12 }}
          {{- if .Values.probes.php.liveness.enabled }}
          livenessProbe:
            exec:
              command: {{ .Values.probes.php.liveness.command }}
            initialDelaySeconds: {{ .Values.probes.php.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.php.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.php.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.php.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.php.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.php.readiness.enabled }}
          readinessProbe:
            exec:
              command: {{ .Values.probes.php.readiness.command }}
            initialDelaySeconds: {{ .Values.probes.php.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.php.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.php.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.php.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.php.readiness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.php.startup.enabled }}
          startupProbe:
            exec:
              command: {{ .Values.probes.php.startup.command }}
            initialDelaySeconds: {{ .Values.probes.php.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.php.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.php.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.php.startup.failureThreshold }}
            successThreshold: {{ .Values.probes.php.startup.successThreshold }}
          {{- end }}
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.sharedVolume.name }}
              mountPath: /var/www/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          {{- if .Values.probes.nginx.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.nginx.liveness.path }}
              port: {{ .Values.probes.nginx.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.nginx.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.nginx.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.nginx.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.nginx.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.nginx.readiness.path }}
              port: {{ .Values.probes.nginx.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.nginx.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.nginx.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.nginx.readiness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.nginx.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.nginx.startup.path }}
              port: {{ .Values.probes.nginx.startup.port }}
            initialDelaySeconds: {{ .Values.probes.nginx.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.nginx.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.nginx.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.nginx.startup.failureThreshold }}
            successThreshold: {{ .Values.probes.nginx.startup.successThreshold }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
