{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-redis
  labels:
    {{- include "wordpress-bedrock.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
