apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-nginx-config
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 8080;
        server_name _;
        root {{ .Values.laravel.config.webRoot }};

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        # Pass PHP scripts to PHP-FPM
        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_hide_header X-Powered-By;
        }

        # Deny access to . files
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
