{{- if .Values.database.enabled }}
apiVersion: "kinda.rocks/v1beta1"
kind: "Database"
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "yii2.labels" . | nindent 4 }}
spec:
  secretName: {{ include "yii2.fullname" . }}-db-credentials
  instance: {{ .Values.database.instance | quote }}
  deletionProtected: {{ .Values.database.deletionProtected }}
  {{- if .Values.database.secretsTemplates }}
  secretsTemplates:
    {{- toYaml .Values.database.secretsTemplates | nindent 4 }}
  {{- end }}
{{- end }}