apiVersion: v1
kind: Service
metadata:
  name: {{ include "yii2.fullname" . }}
  labels:
    {{- include "yii2.labels" . | nindent 4 }}
  {{- if .Values.syncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.application }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yii2.selectorLabels" . | nindent 4 }}
