name: Release Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Create Helm package directory
        run: |
          mkdir -p .cr-release-packages
          mkdir -p .cr-index

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
          if-exists: true

      - name: Copy existing packages
        run: |
          if [ -d "gh-pages" ]; then
            echo "Copying existing packages"
            # Copy all tgz files except index.yaml
            find gh-pages -name "*.tgz" -exec cp {} .cr-release-packages/ \;
          fi

      - name: Package and Update Charts
        run: |
          # First package the common chart
          echo "Packaging common chart"
          helm package common -d .cr-release-packages
          
          # Create charts directory for each chart and copy common chart
          for chart in laravel react wordpress-bedrock yii2; do
            echo "Setting up dependencies for $chart"
            mkdir -p $chart/charts
            cp .cr-release-packages/common-*.tgz $chart/charts/
            
            # Package the chart
            echo "Packaging $chart chart"
            helm package $chart -d .cr-release-packages
          done

      - name: Create/Update Helm Repository Index
        run: |
          echo "Creating new index.yaml"
          helm repo index .cr-release-packages --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          cp .cr-release-packages/index.yaml .cr-index/

      - name: Publish Helm Charts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .cr-release-packages
          target-folder: .
          branch: gh-pages
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ github.actor }}@users.noreply.github.com
          commit-message: "Update Helm repository"
          clean: false

      - name: Publish Helm Repository Index
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .cr-index
          target-folder: .
          branch: gh-pages
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ github.actor }}@users.noreply.github.com
          commit-message: "Update Helm repository index"
          clean: false

      - name: Publish Website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          target-folder: docs
          branch: gh-pages
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ github.actor }}@users.noreply.github.com
          commit-message: "Update Helm charts website"
          clean: false
