{{- define "common.redis.secret" -}}
{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.redis.name" . }}
  labels:
    {{- include "common.redis.labels" . }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
---
{{- end }}
{{- end -}}
