{{- define "common.redis.service" -}}
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.redis.name" . }}
  labels:
    {{- include "common.redis.labels" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "common.redis.selectorLabels" . }}
---
{{- end }}
{{- end -}}
